import React from "react";
import Header from "../components/Header";
import Footer from "../components/Footer";

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 transition-colors duration-200">
      <Header />
      
      <div className="max-w-4xl mx-auto px-4 py-12">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-8">
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-6">Terms of Service</h1>
          <p className="text-gray-600 dark:text-gray-400 mb-8">Last Updated: July 8, 2025</p>

          <div className="space-y-8 text-gray-700 dark:text-gray-300">
            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">1. Acceptance of Terms</h2>
              <p>By accessing or using this website and its services (the "Service"), you agree to be legally bound by these Terms of Service (the "Terms"). If you do not agree to these Terms, you must not use the Service.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">2. Non-Affiliation and No Endorsement</h2>
              <p>This Service is an independent tool and is not affiliated with, endorsed by, or sponsored by OpenAI, its affiliates, or any other third party. All trademarks, service marks, and trade names (including "OpenAI" and "ChatGPT") are the property of their respective owners. Use of these names is for descriptive purposes only and does not imply any association or endorsement.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">3. No Use of OpenAI Intellectual Property</h2>
              <p>The Service does not use, access, or interact with any proprietary technology, API, software, or intellectual property of OpenAI or any other third party. All content generated by the Service is user-created and simulated for illustrative purposes only.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">4. Nature of Service and User Content</h2>
              <p>The Service allows users to create simulated screenshots that resemble ChatGPT conversations. ALL CONTENT GENERATED BY THIS SERVICE IS FICTIONAL AND SIMULATED. The Service does not create, generate, or reproduce actual ChatGPT conversations or responses. Users are solely responsible for the content they create and share using the Service.</p>
              
              <ul className="list-disc list-inside mt-4 space-y-2">
                <li>All generated screenshots are simulated and artificial.</li>
                <li>No actual AI or ChatGPT technology is used to generate responses.</li>
                <li>The Service is a visual mockup tool only.</li>
                <li>Generated content does not represent real ChatGPT capabilities or responses.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">5. Prohibited Uses</h2>
              <p>You agree NOT to use the Service to:</p>
              
              <ul className="list-disc list-inside mt-4 space-y-2">
                <li>Create content intended to deceive, mislead, or defraud others.</li>
                <li>Generate fake evidence for legal proceedings.</li>
                <li>Create content that violates any applicable laws or regulations.</li>
                <li>Harass, defame, or harm any individual or entity.</li>
                <li>Create content that infringes on intellectual property rights.</li>
                <li>Generate content containing hate speech, violence, or illegal activities.</li>
                <li>Impersonate OpenAI, ChatGPT, or any other entity.</li>
                <li>Create content for malicious social engineering or phishing attempts.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">6. Disclosure Requirements</h2>
              <p>Users are REQUIRED to clearly disclose that any generated screenshots are simulated/artificial when:</p>
              
              <ul className="list-disc list-inside mt-4 space-y-2">
                <li>Sharing on social media platforms.</li>
                <li>Using in professional or academic presentations.</li>
                <li>Publishing in any media or publication.</li>
                <li>Using for any commercial purposes.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">7. Intellectual Property and DMCA/Notice & Takedown</h2>
              <p>The Service does not claim ownership over any content generated by users. However, users are solely responsible for ensuring their generated content does not infringe on any third-party intellectual property rights, including but not limited to those of OpenAI or others. If you believe your intellectual property rights have been violated by content generated through this Service, please contact us at fakechatgptsite@gmail.com with sufficient detail, and we will promptly investigate and, if appropriate, remove the allegedly infringing content.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">8. Disclaimers and Limitation of Liability</h2>
              
              <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-2">8.1 Service Provided "As Is"</h3>
              <p className="mb-4">THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT ANY WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR ACCURACY. THE OWNERS EXPRESSLY DISCLAIM ANY LIABILITY FOR THE USE OR MISUSE OF THE SERVICE OR ANY CONTENT GENERATED THEREFROM.</p>
              
              <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-2">8.2 No Liability for User Actions or Third-Party Claims</h3>
              <p>UNDER NO CIRCUMSTANCES SHALL THE OWNERS, OPERATORS, AFFILIATES, OR LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO CLAIMS BY OPENAI OR ANY OTHER THIRD PARTY, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE OR ANY CONTENT GENERATED THEREFROM, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">9. Indemnification</h2>
              <p>You agree to indemnify, defend, and hold harmless the owners, operators, affiliates, and licensors of the Service from and against any and all claims, damages, obligations, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising from or related to: (a) your use of the Service; (b) your violation of these Terms; (c) your violation of any third-party rights, including but not limited to intellectual property rights of OpenAI or any other party; or (d) any content you generate or share using the Service.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">10. Privacy and Data</h2>
              <p>We do not store user-generated conversation content on our servers. All screenshot generation occurs locally in your browser. We may process aggregated, anonymised usage statistics through a third-party analytics platform only after you grant cookie consent. For full details please review our Privacy Policy.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">11. Modification and Termination</h2>
              <p>The owners reserve the right to modify these Terms at any time without prior notice. Continued use of the Service after any such changes constitutes your acceptance of the new Terms. The owners also reserve the right to terminate or suspend access to the Service at any time, for any reason, without liability.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">12. Age Restrictions</h2>
              <p>The Service is intended for users 18 years of age or older. By using the Service, you represent and warrant that you are at least 18 years old.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">13. Governing Law and Jurisdiction</h2>
              <p>These Terms shall be governed by and construed in accordance with the laws of the State of Israel, without regard to its conflict of law principles. Any disputes arising under or in connection with these Terms shall be subject to the exclusive jurisdiction of the competent courts of Tel Aviv, Israel.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">14. Severability and No Waiver</h2>
              <p>If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions shall remain in full force and effect. No waiver of any right or provision of these Terms shall be deemed a further or continuing waiver of such right or provision.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">15. Contact Information</h2>
              <p>If you have any questions about these Terms, or wish to submit a DMCA or takedown notice, please contact us at fakechatgptsite@gmail.com.</p>
            </section>
          </div>

          <div className="mt-8 pt-8 border-t border-gray-200 dark:border-gray-700">
            <div className="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg p-4">
              <p className="text-yellow-800 dark:text-yellow-200 text-sm font-medium">
                ⚠️ Important Legal Notice
              </p>
              <p className="text-yellow-700 dark:text-yellow-300 text-xs mt-2">
                This Service does not collect or store any user data. This Service does not collect or store personal user data. All content is generated locally in your browser. The owners assume no responsibility for user actions or the consequences thereof. Use the Service responsibly and always disclose when content is simulated.
              </p>
            </div>
          </div>
        </div>
      </div>
      
      <Footer />
    </div>
  );
};

export default TermsOfService;